#!/bin/bash

echo "Assignment #2-1, Carlo Alejandro Salazar, masc1415"

#read grades_file	
#read logins_file

grades_file=$1
logins_file=$2

#Find student name with 100 on all assignments
name=`grep 100 $grades_file | cut -d "," -f1`
lastname=`grep 100 $grades_file | cut -d "," -f2`	


#Use student name to find username and password
username=`grep "$name" $logins_file | cut -d "," -f2`
password=`grep "$name" $logins_file | cut -d "," -f3`

echo "$name $lastname"
echo "$username"
echo "$password"
































